### ISSUE TITLE
Gem version?

### ISSUE THREAD

**Issue by datapolitical** [mslinn/jekyll_flexible_include_plugin#3]
I prefer to load my plugins as gems to reduce the number of files I have to worry about locally. Is there any chance this will be updated to support that?

**Comment by mslinn** [comment]
I also would like this to work as a gem, and for the same reason. However, I am busy and for me, that is a nice-to-have feature, not a must-have feature. A PR for this would be happily accepted.

**Comment by mslinn** [comment]
Now available as a gem with v2.0.0. Please see the README.
