### ISSUE TITLE
Liquid tag parsed as text

### ISSUE THREAD

**Issue by datapolitical** [mslinn/jekyll_flexible_include_plugin#4]
I have a liquid tag inside my include which is parsed fine by the normal include but shows up as raw text when using this plugin. Compare https://www.chrisfnicholson.com/recipes/smoked-whole-chicken.html with

http://cfn.io/cfndev.github.io/recipes/smoked-whole-chicken.html and you'll see the liquid `{% picture writeup images/pages/smoked-whole-chicken-1.jpeg 1:1 –alt “making the brine” %} `tags about halfway into the writeup.

**Comment by mslinn** [comment]
Sounds like you want recursive evaluation, is that right? The plugin performs a literal include. If you want to implement recursive evaluation please submit a PR with that feature.
