### ISSUE TITLE
Filenames with Dashes Transformed to Underscores

### ISSUE THREAD

**Issue by AndiH** [mslinn/jekyll_flexible_include_plugin#8]
Thanks for the plugin! It sounds like what I need!

I have one issue, though: I want to include an image into my post, which is located at `assets/img/posts/post-name/image-name.html`. Unfortunately, all dashes / hyphens are transformed into underscores.

So this:

```
{% flexible_include "assets/img/posts/2022-11-02-gpu-compat-matrix/gpu-vendor-model-matrix.table.html" %}
```

fails with this message:

```
Liquid Exception: No such file or directory @ rb_sysopen - [absdir]/assets/img/posts/2022_11_02_gpu_compat_matrix/gpu_vendor_model_matrix.table.html in
```

**Comment by mslinn** [comment]
You found a bug. The workaround is to use this format, which adds the 
name for the first parameter "file=":

|{% flexible_include 
file="assets/img/posts/2022-11-02-gpu-compat-matrix/gpu-vendor-model-matrix.table.html" 
%} |

Mike

**Comment by AndiH** [comment]
That works perfectly!

Thanks for the workaround!
